import * as paraglide from '../paraglide/runtime.js' // generated by paraglide
import * as adapter from './adapter.js'

export type AvailableLanguageTag = paraglide.AvailableLanguageTag
export const availableLanguageTags = paraglide.availableLanguageTags
export const sourceLanguageTag = paraglide.sourceLanguageTag

export function getLanguageTagFromURL(): AvailableLanguageTag | undefined {
    return adapter.getLanguageTagFromURL(availableLanguageTags)
}

export const {LanguageTagProvider, languageTag, setLanguageTag} = adapter.createI18n(paraglide)
